sonar.organization=frapoulay
sonar.projectKey=Frapoulay_ShinyBot
sonar.sources=./modules
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13

# Ignore snake_case rules
sonar.issue.ignore.multicriteria=e1,e2,e3,e4
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S100
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S116
sonar.issue.ignore.multicriteria.e3.ruleKey=python:S117
sonar.issue.ignore.multicriteria.e4.ruleKey=python:S1542
sonar.issue.ignore.multicriteria.e1.resourceKey=**
sonar.issue.ignore.multicriteria.e2.resourceKey=**
sonar.issue.ignore.multicriteria.e3.resourceKey=**
sonar.issue.ignore.multicriteria.e4.resourceKey=**