sonar.organization=frapoulay
sonar.projectKey=Frapoulay_ShinyBot
sonar.sources=./modules
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S117
sonar.issue.ignore.multicriteria.e1.resourceKey=**